server:
  port: 5003

spring:
  application:
    name: SUBMISSION-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/yt_task_submission_service
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver


