server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  server:
#    enableSelfPreservation: false
    renewal-percent-threshold: 0.49
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/